apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-deployment
  namespace: dev
  labels: 
    app: carts-deployment
spec:
  selector:
    matchLabels:
      app: carts-deployment
  replicas: 3
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carts-deployment
    spec:
      containers:
        - name: carts
          image: weaveworksdemos/carts:0.4.8
          ports:
            - containerPort: 80
          securityContext:
            capabilities:
              drop: 
                - all
              add:
                - NET_BIND_SERVICE
          env:
            - name: JAVA_OPTS
              value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false

