apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deployment
  namespace: dev
  labels: 
    app: catalogue-deployment
spec:
  selector:
    matchLabels:
      app: catalogue-deployment
  replicas: 3
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: catalogue-deployment
    spec:
      containers:
        - name: catalogue
          image: 
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              drop: 
                - all
              add:
                - NET_BIND_SERVICE

