apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogue-pvc
  naemspace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

    