apiVersion: apps/v1
kind: Statefulset
metadata:
  name: catalogue-db
  namespace: dev
spec:
  selector:
    matchLabels:
      app: catalogue-db
  serviceName: catalogue-db
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogue-db
    spec:
      containers:
        - name: catalogue-db
          image: weaveworksdemos/catalogue-db:0.3.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password_is_empty
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: true
            - name: MYSQL_DATABASE
              value: socksdb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: catalogue-db-volume
      volumes:
        - name: catalogue-db-volume
          persistentVolumeClaim:
            claimName: catalogue-pvc