apiVersion: v1
kind: PersistentVolume
metadata:
  name: orders-pv
  namespace: dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <insert-AWS-EFS-ID-here>
    