apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: dev
  labels:
    app: payment-deployment
spec:
  selector:
    matchLabels:
      app: payment-deployment
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payment-deployment
    spec:
      containers:
        - name: payment
          image: weaveworksdemos/payment:0.4.3
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE