apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-master-deployment
  namescpace: dev
  labels:
    app: queue-master-deployment
spec:
  selector:
    matchLabels:
      app: queue-master-deployment
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: queue-master-deployment
    spec:
      containers:
        - name: queue-master
          image: weaveworksdemos/queue-master:0.3.1
          ports:
            - containerPort: 80
          securityContext:
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
