apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: dev
  labels: 
    app: user-deployment
spec:
  selector:
    matchLabels:
      app: user-deployment
  replicas: 3
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
        - name: user
          image: weaveworksdemos/user:0.4.4
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              drop: 
                - all
              add:
                - NET_BIND_SERVICE
          env:
            - name: MONGO_HOST
              value: user-db:27017

