apiVersion: apps/v1
kind: Statefulset
metadata:
  name: user-db
  namespace: dev
spec:
  selector:
    matchLabels:
      app: user-db
  serviceName: user-db
  replicas: 1
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-db
          image: weaveworksdemos/user-db:0.4.0
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - mountPath: /data/db
              name: user-db-volume
          securityContext:
            capabilities:
              drop: 
                - all
              add:
                - CHOWN
                - SETGID
                - SETUID
      volumes:
        - name: user-db-volume
          persistentVolumeClaim:
            claimName: user-pvc